### ISSUE TITLE
Implement Declare V3

### ISSUE THREAD

**Issue by gabsn** [focustree/starknet.dart#339]
https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/transactions/

**Comment by rukafe0x** [comment]
gm...can i be assigned?

**Comment by ptisserand** [comment]
> gm...can i be assigned?

Hi @rukafe0x could you please describe how you plan to implement and test declare v3 ?

**Comment by rukafe0x** [comment]
Hi @ptisserand , i'm working on this:

- adding a new argument useSTRKFee to declare function. If this is present and true then will call v3 declare transaction.
- I'm also fixing declare type version 2 test file to support devnet and testing the new declare type version 3.
- adding the new compiled class_hash formula (since sierra 1.5.0 https://github.com/starkware-libs/cairo/pull/4515).
- adding the new transaction type v3 hash formula (https://docs.starknet.io/architecture-and-concepts/network-architecture/transactions/#v3_hash_calculation_2).
- it's almost done and currently working on my local devnet 0.2.0 but not tested against full melos test for compatibility yet.

Please check PR #411 for details. (please don't merge because is not tested with full melos test yet)

Let me know anything to work on that.

**Comment by rukafe0x** [comment]
@ptisserand Please check PR #411 i think it's ready...thanks

**Comment by ptisserand** [comment]
Closed by #423
